- name: Install Docker on EC2
  hosts: web
  become: yes
  tasks:
    - name: Install required packages
      yum:
        name:
          - docker
        state: present

    - name: Start and enable Docker
      service:
        name: docker
        state: started
        enabled: true
